triviaList = [ "jokeEnable", "factEnable", "quoteEnable", "imageEnable", "historyEnable", "dogEnable",]
APINinjasKey = "Fpg1VeRz4ELzZ1F+obZHXQ==7jDp8PXkGiEPzxk9"
prefList = "UHhMeHVYX2dhaGZWdGJ2ag"
debugMode = true
