triviaList = [ "jokeEnable", "factEnable", "quoteEnable", "imageEnable", "historyEnable", "dogEnable",]
APINinjasKey = "Fpg1VeRz4ELzZ1F+obZHXQ==7jDp8PXkGiEPzxk9"
prefList = "MTgxOTg2MjM2NDgwOTg3NTA5OTg6MDow"
debugMode = true
